[package]
name = "nusamai-gpkg"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.3", features = ["sqlite", "runtime-tokio"] }
nusamai-geometry = { path = "../nusamai-geometry" }
thiserror = "1.0.51"

[dev-dependencies]
tokio = { version = "1.35.1", features = ["full"] }
