[package]
name = "nusamai-gpkg"
version = "0.1.0"
edition = "2021"

[dependencies]
sqlx = { version = "0.7.4", features = ["sqlite", "runtime-tokio"] }
nusamai-geometry = { path = "../nusamai-geometry" }
thiserror = "1.0.58"
url = "2.5.0"
indexmap = "2.2.5"

[dev-dependencies]
tokio = { version = "1.36", features = ["full"] }
