[package]
name = "nusamai-kml"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kml = "0.8.5"
shapefile = "0.5.0"
nusamai-geometry = { version = "0.1.0", path = "../nusamai-geometry" }
