[workspace]

[workspace.package]
version = "0.0.0-alpha.0"
authors = ["MIERUNE Inc. <info@mierune.co.jp>"]

members = [
    "app/src-tauri",
    "nusamai-*",
    "nusamai",
]
resolver = "2"

[profile.release-lto]
inherits = "release"
lto = "fat"
panic = "abort"