[workspace]

members = [
    "app/src-tauri",
    "nusamai-geometry",
    "nusamai-gltf",
    "nusamai-geojson",
    "nusamai-geopackage",
    "nusamai-plateau",
    "nusamai-mvt",
    "nusamai-projection",
]
resolver = "2"
