[package]
name = "nusamai-plateau"
version = "0.1.0"
edition = "2021"

[dependencies]
citygml = { path = "./citygml" }
quick-xml = "0.31"

[dev-dependencies]
clap = { version = "4.4", features = ["derive"] }
