[package]
name = "nusamai-plateau"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]

[dependencies]
quick-xml = "0.31"
serde = { version = "1.0.193", features = ["derive"], optional = true }
citygml = { path = "./citygml", features = ["serde"]}

[dev-dependencies]
zstd = "0.13.0"
bincode = { version = "2.0.0-rc", default-features = false, features = ["std", "serde"] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
