[package]
name = "nusamai-plateau"
version.workspace = true
edition = "2021"

[features]
default = ["serde"]

[dependencies]
quick-xml = "0.31.0"
serde = { version = "1.0.193", features = ["derive"], optional = true }
nusamai-citygml = { path = "../nusamai-citygml", features = ["serde"]}
nusamai-geometry = { path = "../nusamai-geometry" }
chrono = { version = "0.4.34", features = ["serde"], default-features = false }
url = "2.5.0"
stretto = "0.8.3"
hashbrown = "0.14.3"
indexmap = "2.2.2"
log = "0.4.20"

[dev-dependencies]
zstd = { version = "0.13.0", features = ["zdict_builder"] }
bincode = { version = "2.0.0-rc", default-features = false, features = ["std", "serde"] }
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
lz4_flex = "0.11.1"
serde_json = "1.0.111"
