[package]
name = "nusamai-plateau"
version = "0.1.0"
edition = "2021"

[features]
default = ["serde"]

[dependencies]
citygml = { path = "./citygml" }
quick-xml = "0.31"
serde = { version = "1.0.193", features = ["derive"], optional = true }

[dev-dependencies]
bincode = { version = "2.0.0-rc", default-features = false, features = ["std", "serde"] }
flate2 = "1.0.28"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0.193", features = ["derive"] }
