[package]
name = "nusamai"
version.workspace = true
edition = "2021"

[dependencies]
indexmap = { version = "2.2.3", features = ["serde"] }
rayon = "1.8.1"
serde = { version = "1.0.196", features = ["derive"] }
nusamai-plateau = { path = "../nusamai-plateau" }
nusamai-citygml = { path = "../nusamai-citygml" }
quick-xml = "0.31.0"
clap = { version = "4.5.0", features = ["derive", "string"] }
thiserror = "1.0.57"
ctrlc = "3.4.2"
bincode = "1.3.3"
lz4_flex = "0.11.2"
nusamai-geojson = { path = "../nusamai-geojson" }
nusamai-gltf-json = { path = "../nusamai-gltf/nusamai-gltf-json" }
nusamai-gltf = { path = "../nusamai-gltf" }
nusamai-3dtiles-json = { path = "../nusamai-3dtiles/nusamai-3dtiles-json" }
nusamai-geometry = { path = "../nusamai-geometry" }
nusamai-czml = { path = "../nusamai-czml" }
nusamai-projection = { path = "../nusamai-projection" }
nusamai-mvt = { path = "../nusamai-mvt" }
geojson = "0.24.1"
serde_json = { version = "1.0.113", features = ["indexmap"] }
url = "2.5.0"
nusamai-gpkg = { path = "../nusamai-gpkg" }
tokio = { version = "1.36", features = ["full"] }
byteorder = "1.5.0"
hashbrown = { version = "0.14.3", features = ["serde"] }
ext-sort = { version = "0.1.4", features = ["memory-limit"] }
deepsize = "0.2.0"
serde_bytes = "0.11.14"
log = { version = "0.4.20" }
pretty_env_logger = "0.5.0"
itertools = "0.12.1"
prost = "0.12.3"
bytesize = "1.3.0"
ahash = "0.8.8"
nusamai-shapefile = { path = "../nusamai-shapefile" }
shapefile = "0.5.0"
earcut-rs = { git = "https://github.com/MIERUNE/earcut-rs.git" }
glob = "0.3.1"
shellexpand = "3.1.0"
kml = "0.8.5"
nusamai-kml = { path = "../nusamai-kml" }

[dev-dependencies]
rand = "0.8.5"
tokio = { version = "1.36", features = ["full"] }
nusamai-geometry = { path = "../nusamai-geometry" }
byteorder = "1.5.0"
glob = "0.3.1"
