[package]
name = "nusamai"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.1.0", features = ["serde"] }
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive"] }
nusamai-plateau = { path = "../nusamai-plateau" }
citygml = { path = "../nusamai-plateau/citygml" }
quick-xml = "0.31.0"
clap = { version = "4.4.11", features = ["derive"] }
thiserror = "1.0.51"
ctrlc = "3.4.1"
bincode = "1.3.3"
lz4_flex = "0.11.1"
nusamai-geojson = { path = "../nusamai-geojson" }
geojson = "0.24.1"
serde_json = "1.0.108"

[dev-dependencies]
rand = "0.8.5"
