[package]
name = "nusamai"
version.workspace = true
edition = "2021"

[dependencies]
indexmap = { version = "2.2.6", features = ["serde", "rayon"] }
rayon = "1.10.0"
serde = { version = "1.0.197", features = ["derive"] }
nusamai-plateau = { path = "../nusamai-plateau" }
nusamai-citygml = { path = "../nusamai-citygml" }
quick-xml = "0.31.0"
clap = { version = "4.5.4", features = ["derive", "string"] }
thiserror = "1.0.58"
ctrlc = "3.4.4"
bincode = { version = "2.0.0-rc.3", default-features = false, features = ["std", "serde"] }
lz4_flex = "0.11.2"
nusamai-geojson = { path = "../nusamai-geojson" }
nusamai-gltf = { path = "../nusamai-gltf" }
nusamai-gltf-json = { path = "../nusamai-gltf/nusamai-gltf-json" }
cesiumtiles = { git = "https://github.com/MIERUNE/cesiumtiles-rs.git" }
nusamai-geometry = { path = "../nusamai-geometry" }
nusamai-czml = { path = "../nusamai-czml" }
nusamai-projection = { path = "../nusamai-projection" }
nusamai-mvt = { path = "../nusamai-mvt" }
nusamai-voxelize = { path = "../nusamai-voxelize" }
fastanvil = "0.31.0"
fastnbt = "2.5.0"
geojson = "0.24.1"
serde_json = { version = "1.0.115", features = ["indexmap"] }
url = "2.5.0"
nusamai-gpkg = { path = "../nusamai-gpkg" }
tokio = { version = "1.36", features = ["full"] }
byteorder = "1.5.0"
hashbrown = { version = "0.14.3", features = ["serde"] }
log = { version = "0.4.21" }
pretty_env_logger = "0.5.0"
itertools = "0.13"
prost = "0.12.3"
bytesize = "1.3.0"
ahash = "0.8.11"
nusamai-shapefile = { path = "../nusamai-shapefile" }
shapefile = "0.6.0"
earcut = "0.4"
glob = "0.3.1"
shellexpand = "3.1.0"
kml = "0.8.5"
nusamai-kml = { path = "../nusamai-kml" }
image = { version = "0.25.0", default-features = false, features = ["rayon", "tiff", "jpeg", "webp", "png"] }
flate2 = "1.0.28"
chrono = "0.4.35"
kv-extsort = { git = "https://github.com/MIERUNE/kv-extsort-rs.git" }
bytemuck = { version = "1.16.0", features = ["derive"] }

[dev-dependencies]
rand = "0.8.5"
tokio = { version = "1.36", features = ["full"] }
nusamai-geometry = { path = "../nusamai-geometry" }
byteorder = "1.5.0"
glob = "0.3.1"
assert_cmd = "2.0.14"
tempfile = "3.10.1"
