[package]
name = "nusamai"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.1.0", features = ["serde"] }
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive"] }

[dev-dependencies]
rayon = "1.8.0"
