[package]
name = "nusamai"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.1.0", features = ["serde"] }
rayon = "1.8.0"
serde = { version = "1.0.193", features = ["derive"] }
nusamai-plateau = { path = "../nusamai-plateau" }
nusamai-citygml = { path = "../nusamai-citygml" }
quick-xml = "0.31.0"
clap = { version = "4.4.11", features = ["derive"] }
thiserror = "1.0.51"
ctrlc = "3.4.1"
bincode = "1.3.3"
lz4_flex = "0.11.1"
nusamai-geojson = { path = "../nusamai-geojson" }
nusamai-geometry = { path = "../nusamai-geometry" }
nusamai-projection = { path = "../nusamai-projection" }
nusamai-mvt = { path = "../nusamai-mvt" }
geojson = "0.24.1"
serde_json = { version = "1.0.108", features = ["indexmap"] }
url = "2.5.0"
nusamai-gpkg = { path = "../nusamai-gpkg" }
tokio = { version = "1.35.1", features = ["full"] }
hashbrown = "0.14.3"
ext-sort = { version = "0.1.4", features = ["memory-limit"] }
deepsize = "0.2.0"
serde_bytes = "0.11.14"
log = { version = "0.4.20" }
pretty_env_logger = "0.5.0"
itertools = "0.12.0"
prost = "0.12.3"
bytesize = "1.3.0"
ahash = "0.8.7"

[dev-dependencies]
rand = "0.8.5"
tokio = { version = "1.35.1", features = ["full"] }
nusamai-geometry = { path = "../nusamai-geometry" }
