[package]
name = "nusamai-czml"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.35", features = ["serde"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = { version = "1.0.114", features = ["float_roundtrip"] }
nusamai-geometry = { path = "../nusamai-geometry" }

[dev-dependencies]
glob = "0.3.1"
