[package]
name = "nusamai-czml"
version = "0.1.0"
edition = "2021"

[dependencies]
nusamai-geometry = { path = "../nusamai-geometry" }
nusamai-gltf = { path = "../nusamai-gltf" }
serde = "1.0.195"
serde_json = { version = "1.0.111", features = ["float_roundtrip"] }

