[package]
name = "nusamai-geojson"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geojson = "0.24.1"
nusamai-geometry = { path = "../nusamai-geometry" }

[dev-dependencies]
clap = { version = "4.4.8", features = ["derive"] }
quick-xml = "0.31.0"
serde_json = "1.0.108"
thiserror = "1.0.50"
