[package]
name = "nusamai-voxelize"
version = "0.1.0"
edition = "2021"

[dependencies]
nusamai-geometry = { path = "../nusamai-geometry" }
earcut = "0.4"
byteorder = "1.5.0"
serde_json = "1.0.115"
nalgebra = "0.32.5"
glam = "0.27.0"
