[package]
name = "nusamai-voxelize"
version = "0.1.0"
edition = "2021"

[dependencies]
nusamai-geometry = { path = "../nusamai-geometry" }
earcut-rs = { git = "https://github.com/MIERUNE/earcut-rs.git", tag = "v0.2.0" }
byteorder = "1.5.0"
serde_json = { version = "1.0.115"}
