[package]
name = "nusamai-gltf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = { version = "1.0.108", features = ["indexmap", "float_roundtrip"] }
serde_repr = "0.1.17"
base64 = "0.21.7"

[dev-dependencies]
glob = "0.3.1"
clap = { version = "4.4.6", features = ["derive"] }
nusamai-geometry = { path = "../nusamai-geometry" }
quick-xml = "0.31.0"
thiserror = "1.0.50"
earcut-rs = { git = "https://github.com/MIERUNE/earcut-rs.git" }
indexmap = "2.1.0"
byteorder = "1.5.0"
