[package]
name = "nusamai-gltf"
edition = "2021"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nusamai-gltf-json = { "path" = "nusamai-gltf-json" }
clap = { version = "4.5.4", features = ["derive"] }
nusamai-geometry = { path = "../nusamai-geometry" }
quick-xml = "0.31.0"
thiserror = "1.0.58"
earcut-rs = { git = "https://github.com/MIERUNE/earcut-rs.git", tag = "v0.3.0" }
indexmap = "2.2.6"
byteorder = "1.5.0"
serde_json = "1.0.115"

[dev-dependencies]
glob = "0.3.1"
