[package]
name = "nusamai-citygml"
version.workspace = true
edition = "2021"

[features]
default = ["serde"]
serde = ["dep:serde", "serde_json", "flatgeom/serde"]

[dependencies]
ahash = "0.8.11"
chrono = { version = "0.4.38", features = ["serde"], default-features = false }
indexmap = { version = "2.6.0", features = ["serde"] }
log = "0.4.22"
macros = { path = "./macros" }
flatgeom = "0.0"
nusamai-projection = { path = "../nusamai-projection"}
quick-xml = "0.37.0"
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0.132", features = ["indexmap"], optional = true }
thiserror = "1.0"
url = { version = "2.5.2", features = ["serde"] }
