name: Test

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env: 
  CARGO_TERM_COLOR: always    

permissions:
  contents: read

jobs:
  bulid_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup update stable
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: install dependencies
        # if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Make Tauri build destination
        run: mkdir -p app/build
      # - name: Build
      #   run: cargo build --verbose --workspace
      - name: Test
        run: cargo llvm-cov --workspace --lcov --output-path lcov.info --all-features
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
