name: Build Tauri App

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

env: 
  CARGO_TERM_COLOR: always    
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: install dependencies
        # if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Make Tauri build destination
        run: mkdir -p app/build
      - name: Build App
        run: cargo build --verbose --package app
      - name: Clippy (lint)
        run: cargo clippy --all-targets --all-features