name: Test Tauri App

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    paths:
      - "app/**"
      - ".github/**"

env: 
  CARGO_TERM_COLOR: always

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rustup
        run: rustup toolchain install stable --profile minimal
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install dependencies
        # if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt install -y libwebkit2gtk-4.0-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Make Tauri build destination
        run: mkdir -p app/build
      - name: Test
        run: cargo llvm-cov --package app --lcov --output-path lcov.info --all-features
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          files: lcov.info
          fail_ci_if_error: false
